### PR TITLE
Ported introspection implementation over from dev.

### PR DESCRIPTION
**Pull request by MonkeyJamboree**

### CODE REVIEW

**Comment by MonkeyJamboree** [comment]
Sorry, please don't merge this yet. I have to work out build issues from Visual Studio.

**Comment by MonkeyJamboree** [comment]
This build works fine (via build.cmd, and afterward using VS), go ahead and merge when appropriate.

**Comment by PinpointTownes** [comment]
I'm currently testing the OWIN/Katana version. I've added a few changes as I was not totally satisfied with the initial approach. It should be merged soon :+1:

**Comment by MonkeyJamboree** [comment]
Sounds good. Anything in particular you weren't satisfied with for my own feedback?

**Comment by PinpointTownes** [comment]
Nothing critical: the `ValidationEndpoint` notification exposed almost no information and was basically useless. Your PR was the opportunity to re-align it with the other notifications, that expose much more information in a strongly-typed way.

I also removed the `client_id` claim, that was abusively using `request.ClientId` (the caller is not necessarily the legitimate holder of the token). But don't worry, I'll open a ticket to reintroduce it later.

**Comment by PinpointTownes** [comment]
Merged: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/commit/b9acde9593eeba55b8274ed46a0dae5156e6ef2a

Thanks! :clap:

**Pull request closed without merging**
