### PR TITLE
Introduce cross-platform RSA key generation

### PR DESCRIPTION
**Pull request by PinpointTownes**
Fixes https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/174.

/cc @sunsided

### CODE REVIEW

**Comment by PinpointTownes** [comment]
@sunsided I tried the fix on Ubuntu and it works like a charm. Now, we'll have to wait for IdentityModel to be fixed :smile:

**Comment by sunsided** [comment]
Damn! Just tried rc1-final today and of course it borks up everything on Linux, while rc2 does the same. 😞
Holding on to my handpicked nightlies here. 😅

**Comment by PinpointTownes** [comment]
Yeah, that sucks and we should blame @brentschmaltz for that :trollface: :facepunch: 

(I also need to fix another IdentityModel bug before releasing ASOS beta4... :cry:)

**Comment by sunsided** [comment]
Ah, as long as "my" nightlies are still on MyGet, everything is OK. :smile:  (I tried fixing all packages to specific versions once - that turned out to be a bad idea as well.) Today was a bit nasty because an update of the xUnit test runner in some of our projects basically triggered a cascade of updates that eventually kicked the authentication right iiiin the face. :smile:

**Comment by PinpointTownes** [comment]
And are you using a fixed version of ASOS as well?

**Comment by sunsided** [comment]
Ah, didn't check the authentication server today, just noticed that the client fails to verify tokens. I do, however, have ASOS on `1.0.0-beta4-0464` at the moment, for some reason I cannot recall right now. 

(And, of course, IdentityModel/OpenIdConnect on `2.0.0-rc1-210120020` and the IdentityModel.Tokens ones on `5.0.0-rc1-210120020` with default automatic token generation enabled. Any newer version and it doesn't work out of the box, as said in the other ticket.)

**Pull request merged**
